# 设置80端口可能会导致运行失败,需要的自行开启
# server:
#   port: 80
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://39.107.102.246:3306/cloudclass?serverTimezone=GMT%2B8
    username: QIT
    password: dy2020@QIT
